version: '3'

services:
  npmsync:
    container_name: npmsync
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./config:/app/config:z
    restart: unless-stopped
