name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest
            type=sha,format=short
            
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: Make package public
        uses: actions/github-script@v6
        with:
          script: |
            const repoName = context.repo.owner.toLowerCase() + '/' + context.repo.repo.toLowerCase();
            const packageName = 'ghcr.io/' + repoName;
            
            await github.request('PATCH /orgs/{org}/packages/container/{package_name}/visibility', {
              org: context.repo.owner,
              package_name: context.repo.repo,
              visibility: 'public'
            }).catch(async e => {
              // If organization request fails, try as user
              await github.request('PATCH /user/packages/container/{package_name}/visibility', {
                package_name: context.repo.repo,
                visibility: 'public'
              }).catch(e => {
                console.log('Failed to set package visibility: ' + e);
              });
            });
